---
# VMtools in Ubuntu 18.04 aren't allowing modification of network addresses
# Ansible playbook to workaround the issue
- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Power on "{{vm_prefix}}-controller1"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller1"
      state: poweredon
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller1"
    delegate_to: localhost

  - pause:
      minutes: 1

- hosts: "{{ temp_vm }}"
  gather_facts: false
  vars_files:
    - envanswer.yml

  tasks:
  - name: Update IP address in /etc/netplan/50-cloud-init.yaml
    shell: sed -i 's/- {{ vm_cidr }}.2\/24/- {{ vm_cidr }}.5\/24/g' /etc/netplan/50-cloud-init.yaml
    become: yes

  - name: Update hostname
    shell: hostnamectl set-hostname '{{ vm_prefix }}'-controller1.home.virtualelephant.com
    become: yes

- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Reboot "{{vm_prefix}}-controller1"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller1"
      state: rebootguest
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller1"
    delegate_to: localhost

# Perform actions on controller2

  - name: Power on "{{vm_prefix}}-controller2"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller2"
      state: poweredon
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller2"
    delegate_to: localhost

  - pause:
      minutes: 1

- hosts: "{{ temp_vm }}"
  gather_facts: false
  vars_files:
    - envanswer.yml

  tasks:
  - name: Update IP address in /etc/netplan/50-cloud-init.yaml
    shell: sed -i 's/- {{ vm_cidr }}.2\/24/- {{ vm_cidr }}.6\/24/g' /etc/netplan/50-cloud-init.yaml
    become: yes

  - name: Update hostname
    shell: hostnamectl set-hostname '{{ vm_prefix }}'-controller2.home.virtualelephant.com
    become: yes

- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Reboot "{{vm_prefix}}-controller2"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller2"
      state: rebootguest
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller2"
    delegate_to: localhost

# Perform arctions on controller3
  - name: Power on "{{vm_prefix}}-controller3"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller3"
      state: poweredon
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller3"
    delegate_to: localhost

  - pause:
      minutes: 1

- hosts: "{{ temp_vm }}"
  gather_facts: false
  vars_files:
    - envanswer.yml

  tasks:
  - name: Update IP address in /etc/netplan/50-cloud-init.yaml
    shell: sed -i 's/- {{ vm_cidr }}.2\/24/- {{ vm_cidr }}.7\/24/g' /etc/netplan/50-cloud-init.yaml
    become: yes

  - name: Update hostname
    shell: hostnamectl set-hostname '{{ vm_prefix }}'-controller3.home.virtualelephant.com
    become: yes

- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Reboot "{{vm_prefix}}-controller3"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller3"
      state: rebootguest
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-controller3"
    delegate_to: localhost

