---
- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Create Anti-affinity rules for controllers
    vmware_vm_vm_drs_rule:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      cluster_name: "{{ cluster_name }}"
      drs_rule_name: "{{ vm_prefix }}-controller-rule"
      vms:
          - "{{ vm_prefix }}-controller1"
          - "{{ vm_prefix }}-controller2"
          - "{{ vm_prefix }}-controller3"
      affinity_rule: False
      enabled: true
      state: present
    delegate_to: localhost

  - name: Create Anti-affinity rules for minions
    vmware_vm_vm_drs_rule:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      cluster_name: "{{ cluster_name }}"
      drs_rule_name: "{{ vm_prefix }}-minion-rule-1"
      vms:
          - "{{ vm_prefix }}-node1"
          - "{{ vm_prefix }}-node2"
          - "{{ vm_prefix }}-node3"
      affinity_rule: False
      enabled: true
      state: present
    delegate_to: localhost

  - name: Create Anti-affinity rules for minions
    vmware_vm_vm_drs_rule:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      cluster_name: "{{ cluster_name }}"
      drs_rule_name: "{{ vm_prefix }}-minion-rule-2"
      vms:
          - "{{ vm_prefix }}-node4"
          - "{{ vm_prefix }}-node5"
          - "{{ vm_prefix }}-node6"
      affinity_rule: False
      enabled: true
      state: present
    delegate_to: localhost

