---
- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Create Ubuntu Kubernetes Controller VMs
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ vm_prefix }}-controller{{item}}"
      template: "{{ ubuntu_template }}"
      datacenter: "{{ dc }}"
      cluster: "{{ cluster_name }}"
      folder: "{{ folder }}"
      datastore: "{{ datastore }}"
      state: poweredoff
    delegate_to: localhost
    register: createvm
    with_sequence: start=1 end=3

