---
- hosts: antrea-cluster
  gather_facts: false
  become: yes

  vars_files:
    - envanswer.yml

  tasks:
  - name: Install NFS-client support
    apt:
      name: ['nfs-common']
      force_apt_get: yes
      state: present
