---
- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  vars:
    folder: "{{ folder }}"
    vm_prefix: "{{ prefix }}"

  tasks:
  - name: Check for existing VM folder
    vmware_folder:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      datacenter: "{{ dc }}"
      cluster: "{{ cluster_name }}"
      folder: "{{ folder }}"
      state: present

  - name: Gather MOID for NSX Logical Switch Portgroup
    vcenter_gather_moids:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      datacenter_name: "{{ dc }}"
      portgroup_name: "{{ switch_name }}"
      validate_certs: False
    register: gather_moids_pg

  - name: Create SSH Bastion Ubuntu VM
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ prefix }}-bastion"
      template: "{{ ubuntu_template }}"
      datacenter: "{{ dc }}"
      cluster: "{{ cluster_name }}"
      folder: "{{ folder  }}"
      networks:
      - name: "{{ portgroup }}"
        ip: "{{ bastion_ip }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        domain: "{{ domain }}"
        type: static
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
    register: create_bastion

  - name: Create Primary DNS Ubuntu VM
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ prefix }}-dns-1"
      template: "{{ ubuntu_template }}"
      datacenter: "{{ dc }}"
      cluster: "{{ cluster_name }}"
      folder: "{{ folder }}"
      networks:
      - name: "{{ portgroup }}"
        ip: "{{ dns1_ip }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        domain: "{{ domain }}"
        type: static
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
    register: createvm

  - name: Create Secondary DNS Ubuntu VM
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ prefix }}-dns-2"
      template: "{{ ubuntu_template }}"
      datacenter: "{{ dc }}"
      cluster: "{{ cluster_name }}"
      folder: "{{ folder }}"
      networks:
      - name: "{{ portgroup }}"
        ip: "{{ dns2_ip }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        domain: "{{ domain }}"
        type: static
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
    register: createvm
