---
# VMtools in Ubuntu 18.04 aren't allowing modification of network addresses
# Ansible playbook to workaround the issue
- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Power on "{{vm_prefix}}-node1"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node1"
      state: poweredon
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node1"
    delegate_to: localhost

  - pause:
      minutes: 1

- hosts: temp105
  gather_facts: false

  tasks:
  - name: Update IP address in /etc/netplan/50-cloud-init.yaml
    shell: sed -i 's/- 10.105.0.2\/24/- 10.105.0.11\/24/g' /etc/netplan/50-cloud-init.yaml
    become: yes

  - name: Update hostname
    shell: hostnamectl set-hostname cilium-node1.home.virtualelephant.com
    become: yes

- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Reboot "{{vm_prefix}}-node1"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node1"
      state: rebootguest
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node1"
    delegate_to: localhost

# Perform actions on node2

  - name: Power on "{{vm_prefix}}-node2"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node2"
      state: poweredon
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node2"
    delegate_to: localhost

  - pause:
      minutes: 1

- hosts: temp105
  gather_facts: false

  tasks:
  - name: Update IP address in /etc/netplan/50-cloud-init.yaml
    shell: sed -i 's/- 10.105.0.2\/24/- 10.105.0.12\/24/g' /etc/netplan/50-cloud-init.yaml
    become: yes

  - name: Update hostname
    shell: hostnamectl set-hostname cilium-node2.home.virtualelephant.com
    become: yes

- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Reboot "{{vm_prefix}}-node2"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node2"
      state: rebootguest
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node2"
    delegate_to: localhost

# Perform actions on node3
  - name: Power on "{{vm_prefix}}-node3"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node3"
      state: poweredon
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node3"
    delegate_to: localhost

  - pause:
      minutes: 1

- hosts: temp105
  gather_facts: false

  tasks:
  - name: Update IP address in /etc/netplan/50-cloud-init.yaml
    shell: sed -i 's/- 10.105.0.2\/24/- 10.105.0.13\/24/g' /etc/netplan/50-cloud-init.yaml
    become: yes

  - name: Update hostname
    shell: hostnamectl set-hostname cilium-node3.home.virtualelephant.com
    become: yes

- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Reboot "{{vm_prefix}}-node3"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node3"
      state: rebootguest
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node3"
    delegate_to: localhost

# Perform actions on node4
  - name: Power on "{{vm_prefix}}-node4"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node4"
      state: poweredon
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node4"
    delegate_to: localhost

  - pause:
      minutes: 1

- hosts: temp105
  gather_facts: false

  tasks:
  - name: Update IP address in /etc/netplan/50-cloud-init.yaml
    shell: sed -i 's/- 10.105.0.2\/24/- 10.105.0.14\/24/g' /etc/netplan/50-cloud-init.yaml
    become: yes

  - name: Update hostname
    shell: hostnamectl set-hostname cilium-node4.home.virtualelephant.com
    become: yes

- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Reboot "{{vm_prefix}}-node4"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node4"
      state: rebootguest
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node4"
    delegate_to: localhost

# Perform actions on node5
  - name: Power on "{{vm_prefix}}-node5"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node5"
      state: poweredon
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node5"
    delegate_to: localhost

  - pause:
      minutes: 1

- hosts: temp105
  gather_facts: false

  tasks:
  - name: Update IP address in /etc/netplan/50-cloud-init.yaml
    shell: sed -i 's/- 10.105.0.2\/24/- 10.105.0.15\/24/g' /etc/netplan/50-cloud-init.yaml
    become: yes

  - name: Update hostname
    shell: hostnamectl set-hostname cilium-node5.home.virtualelephant.com
    become: yes

- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Reboot "{{vm_prefix}}-node5"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node5"
      state: rebootguest
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node5"
    delegate_to: localhost

# Perform actions on node6
  - name: Power on "{{vm_prefix}}-node6"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node6"
      state: poweredon
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node6"
    delegate_to: localhost

  - pause:
      minutes: 1

- hosts: temp105
  gather_facts: false

  tasks:
  - name: Update IP address in /etc/netplan/50-cloud-init.yaml
    shell: sed -i 's/- 10.105.0.2\/24/- 10.105.0.16\/24/g' /etc/netplan/50-cloud-init.yaml
    become: yes

  - name: Update hostname
    shell: hostnamectl set-hostname cilium-node6.home.virtualelephant.com
    become: yes

- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Reboot "{{vm_prefix}}-node6"
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node6"
      state: rebootguest
    delegate_to: localhost

  - name: Wait for VMtools to start
    vmware_guest_tools_wait:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      name: "{{ vm_prefix }}-node6"
    delegate_to: localhost


